version: 2

jobs:
  build:  # required for runs that don't use workflows
    working_directory: ~/workspace
    docker:
      - image: circleci/python:3.6.7  # primary container for the build job
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout  # checkout source code to working directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install --ignore-pipfile --dev
      - run: cd source && PYTHONPATH=. pipenv run pytest --cov . --cov=block_bingo --cov=bluetooth --cov=detection_number --cov=detection_block --cov-branch
      - run: cd source && COVERALLS_REPO_TOKEN=brs6Jjqv1i5atmgyxgsPcxb0jj9dBt4FU pipenv run coveralls

      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
