version: 2

jobs:
  build:  # required for runs that don't use workflows
    working_directory: ~/workspace
    docker:
      - image: circleci/python:3.6  # primary container for the build job
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout  # checkout source code to working directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install --dev
      - run: PYTHONPATH=./src pipenv run pytest --cov src --cov-branch
      - run: COVERALLS_REPO_TOKEN=brs6Jjqv1i5atmgyxgsPcxb0jj9dBt4FU pipenv run coveralls
      - run: mkdir test-results
      - run: PYTHONPATH=./src pipenv run pytest --cov src --cov-branch --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"