name: Pytest and Report coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        version: ${{ matrix.python-version }}
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Install dependencies
      run: |
        pipenv install --python python --ignore-pipfile --dev
    - name: Test with pytest
      run: cd source && PYTHONPATH=. pipenv run pytest --cov=. --cov=block_bingo --cov=bluetooth --cov=detection_number --cov=detection_block --cov-branch --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.0
      with:
        #token: fea0d3fe-4f4d-456b-aee7-5a0f3b5ca3e2 ${{secrets.CODECOV_TOKEN}}
        token: fea0d3fe-4f4d-456b-aee7-5a0f3b5ca3e2
        file: ./source/coverage.xml
        flags: unittests
        name: codecov-umbrella
